(define (problem uav1)
(:domain uav)
(:objects
	base p1 p2 p3 p4 packagecenter r1 r2 uav1 uav2 
)

(:init 
	(at base)
	(= (fuel) 20)
	(= (fuel_capacity) 20)
	(= (packagecount) 2)
	(= (package_capacity) 2)
	(= (cost_surveil) 2)
	(= (cost_intercept) 3)
	(= (num_resolved) 0)
	(= (totalFuelUsage) 0)


	(require_surveil r1)
	(require_surveil r2)
	(require_intercept uav1)
	(require_intercept uav2)
	(require_package p1)
	(require_package p2)
	(require_package p3)
	(require_package p4)


	; DISTANCES
	(= (distance base p1) 4)
	(= (distance base p2) 4)
	(= (distance base p3) 4)
	(= (distance base p4) 4)
	(= (distance base packagecenter) 2)
	(= (distance base r1) 4)
	(= (distance base r2) 5)
	(= (distance base uav1) 5)
	(= (distance base uav2) 3)
	(= (distance p1 base) 4)
	(= (distance p1 p2) 6)
	(= (distance p1 p3) 4)
	(= (distance p1 p4) 8)
	(= (distance p1 packagecenter) 6)
	(= (distance p1 r1) 2)
	(= (distance p1 r2) 7)
	(= (distance p1 uav1) 5)
	(= (distance p1 uav2) 7)
	(= (distance p2 base) 4)
	(= (distance p2 p1) 6)
	(= (distance p2 p3) 8)
	(= (distance p2 p4) 4)
	(= (distance p2 packagecenter) 6)
	(= (distance p2 r1) 6)
	(= (distance p2 r2) 1)
	(= (distance p2 uav1) 9)
	(= (distance p2 uav2) 3)
	(= (distance p3 base) 4)
	(= (distance p3 p1) 4)
	(= (distance p3 p2) 8)
	(= (distance p3 p4) 4)
	(= (distance p3 packagecenter) 2)
	(= (distance p3 r1) 6)
	(= (distance p3 r2) 9)
	(= (distance p3 uav1) 1)
	(= (distance p3 uav2) 5)
	(= (distance p4 base) 4)
	(= (distance p4 p1) 8)
	(= (distance p4 p2) 4)
	(= (distance p4 p3) 4)
	(= (distance p4 packagecenter) 2)
	(= (distance p4 r1) 8)
	(= (distance p4 r2) 5)
	(= (distance p4 uav1) 5)
	(= (distance p4 uav2) 1)
	(= (distance packagecenter base) 2)
	(= (distance packagecenter p1) 6)
	(= (distance packagecenter p2) 6)
	(= (distance packagecenter p3) 2)
	(= (distance packagecenter p4) 2)
	(= (distance packagecenter r1) 6)
	(= (distance packagecenter r2) 7)
	(= (distance packagecenter uav1) 3)
	(= (distance packagecenter uav2) 3)
	(= (distance r1 base) 4)
	(= (distance r1 p1) 2)
	(= (distance r1 p2) 6)
	(= (distance r1 p3) 6)
	(= (distance r1 p4) 8)
	(= (distance r1 packagecenter) 6)
	(= (distance r1 r2) 7)
	(= (distance r1 uav1) 7)
	(= (distance r1 uav2) 7)
	(= (distance r2 base) 5)
	(= (distance r2 p1) 7)
	(= (distance r2 p2) 1)
	(= (distance r2 p3) 9)
	(= (distance r2 p4) 5)
	(= (distance r2 packagecenter) 7)
	(= (distance r2 r1) 7)
	(= (distance r2 uav1) 10)
	(= (distance r2 uav2) 4)
	(= (distance uav1 base) 5)
	(= (distance uav1 p1) 5)
	(= (distance uav1 p2) 9)
	(= (distance uav1 p3) 1)
	(= (distance uav1 p4) 5)
	(= (distance uav1 packagecenter) 3)
	(= (distance uav1 r1) 7)
	(= (distance uav1 r2) 10)
	(= (distance uav1 uav2) 6)
	(= (distance uav2 base) 3)
	(= (distance uav2 p1) 7)
	(= (distance uav2 p2) 3)
	(= (distance uav2 p3) 5)
	(= (distance uav2 p4) 1)
	(= (distance uav2 packagecenter) 3)
	(= (distance uav2 r1) 7)
	(= (distance uav2 r2) 4)
	(= (distance uav2 uav1) 6)
)

(:goal (and 
	(<= (totalFuelUsage) 30)
	(>= (num_resolved) 3)
))


(:metric minimize (totalFuelUsage)
))